language: cpp

os: linux

compiler: gcc

env:
  GNAT: "http://mirrors.cdn.adacore.com/art/5739cefdc7a447658e0b016b"
  GNATCOLL: "http://mirrors.cdn.adacore.com/art/5a15cb87c7a4479a23674d44"

cache:
  ccache: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gnat

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-7
      - python-gnatpython

before_install:
  - mkdir bin
  - ln -s /usr/bin/gcc-7 bin/gcc
  - ln -s /usr/bin/g++-7 bin/g++

install:
  - export GNAT_TOOLS="${TRAVIS_BUILD_DIR}/gnat"
  - ccache -z
  - ccache --max-size=1G
  - |
    #install gnat gpl
    ( set -euo pipefail
      if ! [ -r ${GNAT_TOOLS}/gnat_version \
             -a "${GNAT}" = "$(cat ${GNAT_TOOLS}/gnat_version)" \
             -a -x ${GNAT_TOOLS}/bin/gnat ]
      then
        echo "Downloading GNAT GPL from ${GNAT} ..."
        wget -qO- "${GNAT}" | tar xz
        cd gnat-gpl-2016-x86_64-linux-bin
        make ins-basic prefix=${GNAT_TOOLS}
        echo "${GNAT}" > ${GNAT_TOOLS}/gnat_version
      fi
    )
    export PATH=${GNAT_TOOLS}/bin:${PATH}
    export GPR_PROJECT_PATH=${GNAT_TOOLS}/lib/gnat

  - |
    #build gnatcoll
    ( set -euo pipefail
      if ! [ -r ${GNAT_TOOLS}/gnatcoll_version \
             -a "${GNATCOLL}" = "$(cat ${GNAT_TOOLS}/gnatcoll_version)" \
             -a -d ${GNAT_TOOLS}/lib/gnatcoll ]
      then
        echo "Downloading GNATCOLL from ${GNATCOLL} ..."
        wget -qO- ${GNATCOLL} | tar xz
        cd gnatcoll-gpl-2016-src
        ./configure --prefix=${GNAT_TOOLS} --disable-shared --enable-build=Debug
        make
        make install
        echo "${GNATCOLL}" > ${GNAT_TOOLS}/gnatcoll_version
      fi
    )

  - |
    #build gnat2goto + unit tests
    ( set -euo pipefail
      cd gnat2goto
      make
      gprbuild -P unit_tests.gpr -cargs -largs
    )
    export PATH=$(pwd)/gnat2goto/install/bin:${PATH}

  - |
    #build updated cbmc
    ( set -euo pipefail
      cd ${TRAVIS_BUILD_DIR}/lib/cbmc
      cmake -H. -Bbuild '-DCMAKE_BUILD_TYPE=Release'  '-DCMAKE_CXX_COMPILER=/usr/bin/g++-7'
      cmake --build build --target cbmc -- -j4
    )
    export PATH=${TRAVIS_BUILD_DIR}/lib/cbmc/build/bin:${PATH}

script:
  #run the tests
  - (cd testsuite/gnat2goto; ./testsuite.py --timeout 60 --diffs --enable-color -j 2 )
  - gnat2goto/install/bin/unit_tests

before_cache:
  - ccache -s

deploy:

notifications:
